### ISSUE TITLE
Great minds think alike?

### ISSUE THREAD

**Issue by vwbusguy** [Technohacker/QBSH#1]
I just found your project today and it looks like we have no small amount of overlap.  If you're interested in picking this back up and have some low hanging fruit and/or would like to collaborate on my version of the concept, let me know.  It's cool to see others working in this space. 

https://github.com/vwbusguy/qbsh

**Comment by Technohacker** [comment]
Hey! Thanks for reaching out. It's been quite a while since I've last used QBASIC, so I doubt I would be able to make any changes to this project now :sweat_smile: 
That being said, it's nice to see a fresh project in the same vein, I'll keep an eye out for your version :D
